### ISSUE TITLE
Fix Image Stretching in Events, Courses and  Programs page

### ISSUE THREAD

**Issue by ibkay998** [Sidd2024/Allops#1]
![Screenshot (294)](https://user-images.githubusercontent.com/29078268/193183343-04db09b2-8bdb-47f0-aa90-50786d7470b6.png)

**Comment by Sidd2024** [comment]
Actually it's okay but if you have better option then please raise a respective pr.

**Comment by Csrivastava003** [comment]
I would like to work on this issue under Hacktoberfest

**Comment by Pranshu1902** [comment]
I would love to work on this issue or any other issue related to Django or frontend, under Hacktoberfest

**Comment by Sidd2024** [comment]
this is not a valid issue according to me.
Don't worry you guys can work on other issues soon
