### ISSUE TITLE
Add Build a Climate Fintech App by Rapyd Hacakathons into Allops opportunity.

### ISSUE THREAD

**Issue by rahulchwdhary** [Sidd2024/Allops#13]
Description : Create a Climate Fintech Application, build on your own existing app, marketplace, or platform or create a powerful fintech feature that can be integrated into your Climate app or platform.
EXAMPLES
Using climate APIs computer models to payout climate disaster victims.
Carbon offsetting applications and marketplaces need to pay into wallets and payout to other users.

Official Link : https://rapyd.hackerearth.com/

**Comment by Sidd2024** [comment]
provide official link and keep issue headline short😇

**Comment by Sidd2024** [comment]
Nice, Please add it👍🏻

**Comment by rahulchwdhary** [comment]
Raised PR #14 . Please review and merge.

**Comment by Sidd2024** [comment]
Merged
