### ISSUE TITLE
RoboHacks 2 by MLH

### ISSUE THREAD

**Issue by rahulchwdhary** [Sidd2024/Allops#15]
Description: Hosted by MLH hackathon is a 48-hour hackathon hosted every weekend in our community discord. Visit discord.mlh.io for more details about the ongoing hackathon. Students can include high school students, university undergraduate or postgraduate students, and people who are in vocational training such as apprenticeships.

Official link: https://organize.mlh.io/participants/events/8521-robohacks-2

**Comment by Sidd2024** [comment]
yeah you can go for it!
