### ISSUE TITLE
Courses: FreeCodeCamp -JavaScript

### ISSUE THREAD

**Issue by jose-jimmy** [Sidd2024/Allops#18]
Description: JavaScript is a high-level programming language that all modern web browsers support. It is also one of the core technologies of the web, along with HTML and CSS that you may have learned previously. This section will cover basic JavaScript programming concepts, which range from variables and arithmetic to objects and loops.

Official link: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/

**Comment by Sidd2024** [comment]
yess, you can add it.

**Comment by jose-jimmy** [comment]
Hey @Sidd2024 can you please specify the file structure where I can find the course section

**Comment by Sidd2024** [comment]
@jose-jimmy you can find it on the website [here](https://allops.herokuapp.com/Type/Course)
and if the HTML file [here](https://github.com/Sidd2024/Allops/blob/main/Allops/templates/Allops/opportunities.html)

**Comment by Sidd2024** [comment]
@jose-jimmy you also have to update Added_Opportunities.md respectively...
