### ISSUE TITLE
Button's color changes to blue and white on click

### ISSUE THREAD

**Issue by Sidd2024** [Sidd2024/Allops#19]
Edit button CSS, so that when one clicks on a button the colour changes to a more suitable colour according to the look and feel of the website or just adding some extra box-shadow should be fine as well. ✨

**Comment by aniket2003** [comment]
@Sidd2024 Could you please assign me with this task I would like to work on this.

**Comment by Igdtuwresource** [comment]
@Sidd2024 assign me the task please. I am a web developer , can do this surely.

**Comment by Igdtuwresource** [comment]
@Sidd2024 please assign me the task. I am a web developer, knows CSS very well.

**Comment by DhruvDhari** [comment]
i am very new to github, but i know about box shadow,text shadow,transition stuff..
How can i contribute on this one?

**Comment by Sidd2024** [comment]
> @Sidd2024 Could you please assign me with this task I would like to work on this.

go for it

**Comment by Sidd2024** [comment]
srry guys I can assign this type of issue to only a single person

**Comment by aniket2003** [comment]
@Sidd2024 I am really sorry for wasting your time , I can't work right now ,I am unassigning my self again I am really sorry.

**Comment by Sidd2024** [comment]
@Igdtuwresource you want work on it?

**Comment by jagrut-sharma** [comment]
@Sidd2024 I can help with this issue. I am a beginner but I know enough CSS to help with this issue. Could you please assign it to me?

**Comment by Sidd2024** [comment]
@jagrut-sharma okay you can work on this!

**Comment by jagrut-sharma** [comment]
I have created a pull request. Please check
