### ISSUE TITLE
Fix: Weird Stretched Banner Images In Compete,Event,Programs,Course Pages

### ISSUE THREAD

**Issue by ST1LLWATER** [Sidd2024/Allops#29]
The banner images look stretched and wierd in hero section of the pages, Ill fix them so they look more better and pretty.
`Sample Of the Issue`
![image](https://user-images.githubusercontent.com/62516824/194099064-0bca8836-e892-44e7-ad02-6000bfe6ba34.png)

**Comment by ST1LLWATER** [comment]
Please assign this issue to me and add required labels.

**Comment by Sidd2024** [comment]
@ST1LLWATER okay you can work on this👍🏻
make sure to ⭐ this repo....
