### ISSUE TITLE
Contributers.md and Code of Conduct files are missing !!

### ISSUE THREAD

**Issue by sumitbishti** [Sidd2024/Allops#3]
Contributors.md file is missing as per the Hacktoberfest Guidelines.

The repo should have a contributing.md file where contributors can add their name.

I can create a very good file with all the important guidelines of contributing towards the project.

**Comment by sumitbishti** [comment]
Code of Conduct file is also missing. Please assign this issue to me.

**Comment by Sidd2024** [comment]
Yeah i was going to add them today but if you want then you can add them..

**Comment by sumitbishti** [comment]
Sure i will add them. Just add some hacktoberfest labels on your issues.

**Comment by sumitbishti** [comment]
Hey, you shouldn't be doing this. You had already assigned it to me.

**Comment by Sidd2024** [comment]
don't worry you can still improve contributing.md and raise a pr
