### ISSUE TITLE
Twitter and YouTube link not working

### ISSUE THREAD

**Issue by prakhar-1005** [Sidd2024/Allops#31]
The links for the twitter and YouTube are not working. I would like to fix them. Also, please provide me the links to be added.

Screenshot:
![Screenshot (38)_LI](https://user-images.githubusercontent.com/94559623/194108829-9e436ed7-8ac2-4a94-9e57-6dc6398b509c.jpg)

**Comment by Sidd2024** [comment]
Well that's because Allops don't exist on these platforms yet so there are no links for them😅

**Comment by prakhar-1005** [comment]
Oh!
