### ISSUE TITLE
Smart India Hackathon

### ISSUE THREAD

**Issue by Sarita-Singh** [Sidd2024/Allops#32]
Description: Nationwide initiative to provide a platform to solve some of the pressing problems we face in our daily lives, and thus enhance the mindset of problem-solving. It aims to inculcate the culture of startup and innovation ecosystem across two age groups: Jr(School students from 6th-12th class), Sr(students pursuing Graduate/Post-Graduate/Ph.D). Visit SIH official website for more details. 

Official link: https://sih.gov.in/

**Comment by Sidd2024** [comment]
SIH is finished for 2022, It have to be an upcoming opportunity...
