### ISSUE TITLE
Spelling error on Allops page

### ISSUE THREAD

**Issue by Sarita-Singh** [Sidd2024/Allops#33]
Hey,
'professionals' is misspelt as 'proffestinals' as shown in the attached screenshot. You can assign me to correct this.

![Screenshot from 2022-10-05 22-15-44](https://user-images.githubusercontent.com/75107393/194116221-eecfa1c8-b138-4514-a11f-717ad5ad3cc8.png)

**Comment by Sidd2024** [comment]
yes please correct it
