### ISSUE TITLE
Add opportunity Optum Stratethon Season 4

### ISSUE THREAD

**Issue by Sarita-Singh** [Sidd2024/Allops#35]
Description: Stratethon Season 4 is open to students from engineering schools and business schools across India, the Philippines, Singapore, and Malaysia. It is live from 22 Sep 22, 12:00 PM IST to 15 Nov 22, 08:00 PM IST.

Official link: https://www.optum.com/

**Comment by Sidd2024** [comment]
@Sarita-Singh okay you can add it!
