### ISSUE TITLE
Text is not legible 

### ISSUE THREAD

**Issue by LunarMarathon** [Sidd2024/Allops#4]
The text in the filter dropdown is not legible due to the visibility of text in the cards behind it. I've attached the screenshots: 

![i1](https://user-images.githubusercontent.com/113847439/193273464-11042703-262c-47c2-bb70-1f56f3b4775c.png)
![i2](https://user-images.githubusercontent.com/113847439/193273503-a620fccb-68b9-4ad8-80b2-76f479e04aa0.png)

I can fix this issue, please assign it to me

**Comment by Sidd2024** [comment]
I'll soon list some more issues to work on and I will also add the required tags and docs as per hacktoberfest guidelines.
