### ISSUE TITLE
Bookmarks admin section fix

### ISSUE THREAD

**Issue by NabhyaKhoria** [Sidd2024/Allops#40]
1. In Django Admin Panel, saves (bookmarks) proper naming of the model. Currently it just refers to save object (xx)
2. Increase size of cards and decrease the margin between them, for more clarity and visibility.

**Comment by Sidd2024** [comment]
hello @NabhyaKhoria thanks for your time👋🏻

1 Yes renaming save as bookmark would be appreciated but be careful because you have to apply changes to a lot of files in django to keep it error-free.

2 You can also enhance the cards but make sure that the content fits properly like now!😊
