### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by NabhyaKhoria** [Sidd2024/Allops#49]
There is no .gitignore file, which is crucially important for a repository. Please assign me to upload a gitignore file, which will prevent any sql or pyc files to get uploaded in the repository.

**Comment by priyanshusingh305** [comment]
Hi @Sidd2024,
I would like to work on this issue.

**Comment by priyanshusingh305** [comment]
@Sidd2024 if you have any other issue please mention me in.

**Comment by Sidd2024** [comment]
@NabhyaKhoria yeah sure go for it!

**Comment by Sidd2024** [comment]
hey there! @priyanshusingh305 @NabhyaKhoria is not a maintainer so you are welcome to work on other current or upcoming issues. Also, This type of issue can be assigned to one person at a time😇
