### ISSUE TITLE
GDG related inperson event notification

### ISSUE THREAD

**Issue by mohityogi212** [Sidd2024/Allops#50]
Here i will let allops audience get to know about inperson events.
Google devfest
Hereis the link of one of those 
https://developers.google.com/community/devfest#find-a-devfest-community-near-you

An annual event hosted by the across the world to bring the technology closer to the developers. It is an all day developer conference where we aim to focus on multiple technologies through lightning talks sessions workshops etc.

https://gdg.community.dev/events/details/google-gdg-jalandhar-presents-devfest-jalandhar-2022/

**Comment by Sidd2024** [comment]
@mohityogi212 yess please add it!
